# Generated by Django 3.2 on 2023-02-07 19:55

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, validators=[core.validators.validate_release_year]),
        ),
    ]
